<?php

namespace Tests\Unit;

use App\Services\OrderService;
use PHPUnit\Framework\TestCase;

class CreateOrderTest extends TestCase
{
    protected OrderService $orderService;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->orderService = new OrderService();
    }

    /**
     * A basic unit test example.
     */
    public function test_create_order(): void
    {
        //Arrange
        $firstName = 'Vardenis';
        $lastName = 'Pavardenis';
        $country = 'USA';
        $region = 'California';
        $address = 'Haha st. 5, El Segundo';

        //Act
        $this->orderService->create($firstName, $lastName, $country, $region, $address);

        $this->assertDatabaseHas('orders', [
            'first_name' => $firstName,
            'last_name' => $lastName,
            'country' => $country,
           'region' => $region,
           'address' => $address
            ]);
    }
}
